// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromotorSelection.Infrastructure;

#nullable disable

namespace PromotorSelection.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427095023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromotorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeamId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priorytet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromotorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Promotor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStudentow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Promotorzy");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NrAlbumu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SredniaOcen")
                        .HasColumnType("REAL");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RozmiarZespołu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaTematu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromotorId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypKontaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.Promotor", "Promotor")
                        .WithMany("Przydzialy")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromotorSelection.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("PromotorSelection.Domain.Entities.Team", "Team")
                        .WithMany("Przydzialy")
                        .HasForeignKey("TeamId");

                    b.Navigation("Promotor");

                    b.Navigation("Student");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Preference", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.Promotor", "Promotor")
                        .WithMany()
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromotorSelection.Domain.Entities.Student", "Student")
                        .WithMany("Wybory")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Promotor", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.User", "User")
                        .WithOne("Promotor")
                        .HasForeignKey("PromotorSelection.Domain.Entities.Promotor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Student", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.Team", "Team")
                        .WithMany("Studenci")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PromotorSelection.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("PromotorSelection.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Topic", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.Promotor", "Promotor")
                        .WithMany("Tematy")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.User", b =>
                {
                    b.HasOne("PromotorSelection.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Promotor", b =>
                {
                    b.Navigation("Przydzialy");

                    b.Navigation("Tematy");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Student", b =>
                {
                    b.Navigation("Wybory");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.Team", b =>
                {
                    b.Navigation("Przydzialy");

                    b.Navigation("Studenci");
                });

            modelBuilder.Entity("PromotorSelection.Domain.Entities.User", b =>
                {
                    b.Navigation("Promotor");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
